server:
  port: 8769

spring:
  profiles: peer2
eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: peer2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/