---
spring:
  profiles: peer1 # 指定profile=peer1
  application:
    name: Eureka-Server
server:
  port: 8761 # 注册服务的端口号
eureka:
  instance:
    hostname: peer1 # 指定当profile=peer1时，主机名
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/ # 将自己注册到peer2这个Eureka上面去

---
spring:
  profiles: peer2
  application:
    name: Eureka-Server
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/ # 服务注册地址，将自己注册到peer2上去